name: work_in
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- FIREBASE PACKAGES (Added) ---
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # --- MAP PACKAGES (Moved here) ---
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    # Agar services ki images bhi hain to unka folder bhi add karein
    # - assets/services/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-SemiBold.ttf
          weight: 600

# --- Native Splash (White screen only) ---
flutter_native_splash:
  color: "#ffffff"